(define (problem terraria)
(:domain terraria)
(:objects 
	cobweb1 - cobweb iron1 - iron_bar lead1 - lead_bar chain1 - chain platinum1 - platinum_bar
	silk1 - silk bed1 - bed sword1 - platinum_sword
	wood1 - wood chest1 - chest MahoganyWood - mahogany_wood IvyChest - ivy_chest
	Home Workshop Forest MahoganyForest Mine - location
)
(:bounds 
	(<= (w) 100)
	(<= (chain_found) 10)
	(<= (iron) 60)
	(<= (lead) 60)
	(<= (platinum) 60)
	(<= (cob) 60)
	(<= (beds) 30)
	(>= (w) 5)
	(>= (chain_found) 1)
	(>= (iron) 5)
	(>= (lead) 5)
	(>= (platinum) 5)
	(>= (cob) 10)
	(>= (beds) 3)
)
(:precision 
	(= (w) 0)
	(= (chain_found) 0)
	(= (iron) 0)
	(= (lead) 0)
	(= (platinum) 0)
	(= (cob) 0)
	(= (beds) 0)
)
(:init
	(= (numeric_goal_bed) 125)
	(= (numeric_goal_ivy) 125)
	(= (numeric_goal_chest) 125)
	(= (numeric_goal_sword) 125)
	(= (stock cobweb1) 0)
	(= (stock iron1) 0)
	(= (stock MahoganyWood) 0)
	(= (stock lead1) 0)
	(= (stock chain1) 0)
	(= (stock silk1) 0)
	(= (stock platinum1) 0)
	(= (stock bed1) 0)
	(= (stock sword1) 0)
	(= (stock chest1) 0)
	(= (stock wood1) 0)
	(= (stock IvyChest) 0)
	(can_assemble Workshop)
	(can_lumber Forest)
	(can_lumber_mahogany MahoganyForest)
	(can_mine Mine)
	(at Home)
	(ready_workbench)
)
(:goal (and
	(placed_swords) (placed_beds) (placed_chests) (placed_ivy_chests)
))
)

